[package]
name = "trippy"
version = "0.7.0-dev"
authors = ["FujiApple <fujiapple852@gmail.com>"]
description = "A network diagnostic tool"
documentation = "https://github.com/fujiapple852/trippy"
homepage = "https://github.com/fujiapple852/trippy"
repository = "https://github.com/fujiapple852/trippy"
keywords = ["cli", "tui", "traceroute", "ping", "icmp"]
categories = ["command-line-utilities", "network-programming"]
readme = "README.md"
license = "Apache-2.0"
edition = "2021"

[[bin]]
bench = false
path = "src/main.rs"
name = "trip"

[dependencies]

# Library dependencies
socket2 = { version = "0.4.7", features = [ "all" ] }
thiserror = "1.0.32"
derive_more = "0.99.17"
arrayvec = "0.7.2"

# TUI dependancies
anyhow = "1.0.66"
dns-lookup = "1.0.8"
trust-dns-resolver = "0.22.0"
crossbeam = "0.8.2"
clap = { version = "4.0.24", features = [ "derive", "wrap_help", "cargo" ] }
humantime = "2.1.0"
parking_lot = "0.12.1"
tui = "0.18.0"
crossterm = "0.23.2"
chrono = { version = "0.4.22", default-features = false, features = [ "clock" ] }
itertools = "0.10.3"
serde = { version = "1.0.147", features = [ "derive" ] }
serde_json = "1.0.87"
comfy-table = "6.1.2"

# Library dependancies (Linux)
[target.'cfg(target_os = "linux")'.dependencies]
caps = "0.5.5"

# Library dependancies (Unix)
[target.'cfg(target_family = "unix")'.dependencies]
nix = { version = "0.25.0", default-features = false, features = [ "user", "poll", "net" ] }

[dev-dependencies]
rand = "0.8.5"