[package]
name = "trippy"
version = "0.7.0-dev"
authors = ["FujiApple <fujiapple852@gmail.com>"]
description = "A network diagnostic tool"
documentation = "https://github.com/fujiapple852/trippy"
homepage = "https://github.com/fujiapple852/trippy"
repository = "https://github.com/fujiapple852/trippy"
keywords = ["cli", "tui", "traceroute", "ping", "icmp"]
categories = ["command-line-utilities", "network-programming"]
readme = "README.md"
license = "Apache-2.0"
edition = "2021"

[[bin]]
bench = false
path = "src/main.rs"
name = "trip"

[dependencies]

# Library dependencies
thiserror = "1.0.32"
derive_more = "0.99.17"
arrayvec = "0.7.2"

# TUI dependencies
anyhow = "1.0.66"
dns-lookup = "1.0.8"
trust-dns-resolver = "0.22.0"
crossbeam = "0.8.2"
clap = { version = "4.0.29", features = [ "derive", "wrap_help", "cargo" ] }
humantime = "2.1.0"
parking_lot = "0.12.1"
tui = "0.18.0"
crossterm = "0.23.2"
chrono = { version = "0.4.23", default-features = false, features = [ "clock" ] }
itertools = "0.10.3"
serde = { version = "1.0.150", features = [ "derive" ] }
serde_json = "1.0.89"
comfy-table = "6.1.3"

# Library dependencies (Linux)
[target.'cfg(target_os = "linux")'.dependencies]
caps = "0.5.5"

# Library dependencies (Unix)
[target.'cfg(unix)'.dependencies]
nix = { version = "0.26.1", default-features = false, features = [ "user", "poll", "net" ] }
socket2 = { version = "0.4.7", features = [ "all" ] }

[target.'cfg(windows)'.dependencies.windows]
version = "0.43.0"
features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_System_IO",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_System_IO",
    "Win32_System_Threading",
]

[dev-dependencies]
rand = "0.8.5"