[package]
name = "trippy"
version = "0.9.0-dev"
authors = ["FujiApple <fujiapple852@gmail.com>"]
description = "A network diagnostic tool"
documentation = "https://github.com/fujiapple852/trippy"
homepage = "https://github.com/fujiapple852/trippy"
repository = "https://github.com/fujiapple852/trippy"
keywords = ["cli", "tui", "traceroute", "ping", "icmp"]
categories = ["command-line-utilities", "network-programming"]
readme = "README.md"
license = "Apache-2.0"
edition = "2021"
exclude = ["assets/"]

[[bin]]
bench = false
path = "src/main.rs"
name = "trip"

[dependencies]

# Library dependencies
thiserror = "1.0.44"
derive_more = "0.99.17"
arrayvec = "0.7.4"
socket2 = { version = "0.5.2", features = [ "all" ] }
tracing = "0.1.37"

# TUI dependencies
anyhow = "1.0.72"
dns-lookup = "2.0.1"
trust-dns-resolver = "0.22.0"
crossbeam = "0.8.2"
clap = { version = "4.3.4", features = [ "derive", "wrap_help", "cargo" ] }
clap_complete = "4.3.1"
humantime = "2.1.0"
parking_lot = "0.12.1"
ratatui = "0.22.0"
crossterm = "0.26.1"
chrono = { version = "0.4.26", default-features = false, features = [ "clock" ] }
itertools = "0.11.0"
serde = { version = "1.0.168", features = [ "derive" ] }
serde_json = "1.0.104"
comfy-table = "7.0.1"
strum = { version = "0.25.0", features = [ "derive" ] }
etcetera = "0.8.0"
toml = "0.7.6"
indexmap = "2.0.0"
maxminddb = "0.23.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
tracing-chrome = "0.7.1"

# Library dependencies (Linux)
[target.'cfg(target_os = "linux")'.dependencies]
caps = "0.5.5"

# Library dependencies (Unix)
[target.'cfg(unix)'.dependencies]
nix = { version = "0.26.2", default-features = false, features = [ "user", "poll", "net" ] }

# Library dependencies (Windows)
[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.48.0"
features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_System_IO",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_System_IO",
    "Win32_System_Threading",
]

[target.'cfg(windows)'.dependencies]
widestring = "1.0.2"
paste = "1.0.14"

[dev-dependencies]
rand = "0.8.5"
test-case = "3.1.0"

# cargo-generate-rpm dependencies
[package.metadata.generate-rpm]
assets = [
  { source = "target/release/trip", dest = "/usr/bin/trip", mode = "755" },
]
