[package]
name = "trippy"
version = "0.9.0-dev"
authors = ["FujiApple <fujiapple852@gmail.com>"]
description = "A network diagnostic tool"
documentation = "https://github.com/fujiapple852/trippy"
homepage = "https://github.com/fujiapple852/trippy"
repository = "https://github.com/fujiapple852/trippy"
keywords = ["cli", "tui", "traceroute", "ping", "icmp"]
categories = ["command-line-utilities", "network-programming"]
readme = "README.md"
license = "Apache-2.0"
edition = "2021"
exclude = ["assets/"]

[[bin]]
bench = false
path = "src/main.rs"
name = "trip"

[dependencies]

# Library dependencies
arrayvec = { version = "0.7.4", default-features = false }
derive_more = { version = "0.99.17", default-features = false, features = [ "mul", "add", "add_assign" ] }
socket2 = { version = "0.5.5", default-features = false }
thiserror = "1.0.50"
tracing = { version = "0.1.40", default-features = false }

# TUI dependencies
anyhow = "1.0.75"
dns-lookup = "2.0.4"
hickory-resolver = "0.24.0"
crossbeam = "0.8.2"
clap = { version = "4.4.0",  default-features = false, features = [ "cargo", "derive", "wrap_help", "usage", "unstable-styles" ] }
clap_complete = "4.4.4"
humantime = "2.1.0"
parking_lot = "0.12.1"
ratatui = "0.24.0"
crossterm = { version = "0.27.0",  default-features = false, features = [ "events", "windows" ] }
chrono = { version = "0.4.31", default-features = false, features = [ "clock" ] }
itertools = "0.12.0"
serde = { version = "1.0.193", default-features = false }
serde_json = { version = "1.0.108", default-features = false }
comfy-table = { version = "7.1.0", default-features = false }
strum = { version = "0.25.0", default-features = false, features = [ "std", "derive" ] }
etcetera = "0.8.0"
toml = { version = "0.8.8", default-features = false, features = [ "parse" ] }
indexmap = { version = "2.1.0", default-features = false }
maxminddb = "0.23.0"
tracing-subscriber = { version = "0.3.18", default-features = false, features = [ "json", "env-filter" ] }
tracing-chrome = "0.7.1"
petgraph = "0.6.4"

# Library dependencies (Linux)
[target.'cfg(target_os = "linux")'.dependencies]
caps = "0.5.5"

# Library dependencies (Unix)
[target.'cfg(unix)'.dependencies]
nix = { version = "0.27.1", default-features = false, features = [ "user", "poll", "net" ] }

# Library dependencies (Windows)
[target.'cfg(windows)'.dependencies]
paste = "1.0.14"
widestring = "1.0.2"
windows-sys = { version = "0.48.0", features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_System_IO",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_System_IO",
    "Win32_System_Threading",
] }

[dev-dependencies]
hex-literal = "0.4.1"
rand = "0.8.5"
test-case = "3.3.1"

# cargo-generate-rpm dependencies
[package.metadata.generate-rpm]
assets = [
  { source = "target/release/trip", dest = "/usr/bin/trip", mode = "755" },
]
